LOCATION_COUNT = 150
TAMANHO_FROTA = 3
DEPOSITO_CENTRO = True
POPULATION_SIZE = 100
ELITISM = 10 
SEX_CHANCE = 0.25
EXCLUSIVE_CROSS = True
MAJOR_MUTATION_RATE = 0.5
EXCLUSIVE_MAJOR = True
MINOR_MUTATION_RATE = 1
GENERATIONS = 1000

